#!/usr/bin/env python3
"""
WoW Auto-Namer for IDA Pro 9.1
================================
Reads offset/filename mapping files generated by the AutoDump tool
and applies meaningful names to addresses in the IDA database.

Usage:
    File -> Script file... -> wow_namer.py

    Or from the Python console:
        import wow_namer
        wow_namer.run()

Files processed (searched in the same directory as the IDA database):
  - wow_offsets.txt        : Extracted offsets (Lua, bindings, globals, static)
  - wow_loader_exports.txt : loader.dll export names
  - wow_loader_functions.txt : Internal loader functions

Format expected (all files):
    Name = 0xHEXADDRESS
    Comment lines starting with "//" are ignored.
    Section headers like "// === SECTION NAME ===" are ignored.
"""

import os
import re
import idc
import idaapi
import idautils

# ── Pattern: "Name = 0xHEXADDRESS" ──
LINE_PATTERN = re.compile(r'^\s*(\w[\w.@?$]*)\s*=\s*0x([0-9A-Fa-f]+)\s*$')


def get_image_base() -> int:
    """Return the base address of the current IDB."""
    return idaapi.get_imagebase()


def load_offset_file(filepath: str) -> list[tuple[str, int]]:
    """
    Parse a wow_*.txt offset file.
    Returns list of (name, rva) tuples.
    """
    entries = []
    if not os.path.isfile(filepath):
        print(f"[wow_namer] File not found: {filepath}")
        return entries

    with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
        for lineno, line in enumerate(f, 1):
            line = line.strip()
            # Skip empty lines and comments
            if not line or line.startswith('//'):
                continue
            m = LINE_PATTERN.match(line)
            if m:
                name = m.group(1)
                try:
                    rva = int(m.group(2), 16)
                except ValueError:
                    print(f"[wow_namer]  Skipping line {lineno}: bad hex '{m.group(2)}'")
                    continue
                entries.append((name, rva))
            else:
                # Non-matching non-comment line – might be a section header, just log at debug
                pass

    print(f"[wow_namer]  Loaded {len(entries)} entries from {os.path.basename(filepath)}")
    return entries


def apply_names(entries: list[tuple[str, int]], base: int) -> int:
    """
    Apply names from (name, rva) list at image_base + rva.
    Skips if name is already taken or address is invalid.
    Returns count of successfully named entries.
    """
    renamed = 0
    skipped = 0

    for name, rva in entries:
        ea = base + rva

        # Sanity: address must be within a loaded segment
        if not idc.is_loaded(ea):
            skipped += 1
            continue

        # Check if already named with something meaningful
        existing = idc.get_name(ea, idc.GN_VISIBLE)
        if existing and existing != f"sub_{rva:X}" and not existing.startswith("unk_"):
            # Already has a good name – skip to avoid overwriting manual work
            skipped += 1
            continue

        # Apply the name (SN_NOWARN = don't warn if already named)
        ok = idc.set_name(ea, name, idc.SN_NOWARN | idc.SN_NOCHECK)
        if ok:
            renamed += 1
        else:
            skipped += 1

    return renamed


def run():
    """Main entry point – load all offset files and apply names."""
    
    # ── Determine search directory (same as IDB) ──
    idb_path = idc.get_idb_path()
    search_dir = os.path.dirname(idb_path) if idb_path else os.getcwd()
    
    print("=" * 56)
    print("  WoW Auto-Namer for IDA Pro 9.1")
    print("=" * 56)
    print(f"  Searching: {search_dir}")
    print()
    
    base = get_image_base()
    print(f"  Image base: 0x{base:X}")
    print()

    files_to_process = [
        "wow_offsets.txt",
        "wow_loader_exports.txt",
        "wow_loader_functions.txt",
    ]

    total_renamed = 0
    total_entries = 0

    for fname in files_to_process:
        fpath = os.path.join(search_dir, fname)
        entries = load_offset_file(fpath)
        if not entries:
            continue
        total_entries += len(entries)
        renamed = apply_names(entries, base)
        total_renamed += renamed
        label = os.path.splitext(fname)[0]
        print(f"  [{label}] {renamed}/{len(entries)} names applied")
        print()

    # ── Also try common dump directories as fallback ──
    # If the idb is somewhere else, check the AutoDump directory
    alt_dirs = [
        os.path.join(os.path.dirname(idb_path), "..") if idb_path else None,
    ]
    for alt in alt_dirs:
        if alt and os.path.isdir(alt):
            for fname in files_to_process:
                fpath = os.path.join(alt, fname)
                if os.path.isfile(fpath) and fpath not in [
                    os.path.join(search_dir, f) for f in files_to_process
                ]:
                    entries = load_offset_file(fpath)
                    if entries:
                        total_entries += len(entries)
                        renamed = apply_names(entries, base)
                        total_renamed += renamed
                        print(f"  (fallback) {renamed}/{len(entries)} from {fpath}")

    print("─" * 56)
    print(f"  Done: {total_renamed}/{total_entries} names applied to database")
    print("=" * 56)


# ── Allow running as a script ──
if __name__ == "__main__":
    run()
